[package]
name = "wfc"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
rand = "*"

clap = { version = "4.0", features = ["derive"] }

rustacuda = "0.1"
rustacuda_core = "0.1"
rustacuda_derive = "0.1"
